#include "app/FAQs.h"
#include "app/FAQOption.h"
#include <vector>

namespace app 
{

const std::vector<FAQTopic>& FAQ_topics()
{
    static const std::vector<FAQTopic> topics = 
    {
        { FAQMenuOption::WhyShouldIUse, 
          "Why should I use this?",
          "A common misconception is that this should be used instead of a traditional, online password manager. It can be, but it doesn't have to be.\nFor example, I don't use it instead of an online one - online ones are great as they can be accessed effectively anywhere, and that has a lot of obvious advantages.\n-> So, what should I use it for?\nI often like to encrypt sensitive files on my computer by encrypting them with *7-Zip*, a compression file archiver, which you can use and password protect files.\nFor example, you might keep a scan of a driver's license on your computer, but just having this exposed can be dangerous, so you can use 7-Zip to encrypt the file with a password. Then, you can use Terminally->Locked to generate a password for it.\nYou also don't need to have a single vault! Let's say you have a directory structure with many sensitive files:\n- IDs\n- Identification numbers (i.e. Social Security/National Insurance)\n- Legal documents (contracts)\n- Payslips\nInstead of just exposing these on your computer, you could then have the following in each directory:\n- files.7z (i.e. the encrypted file containing your documents)\n- vault.dat (your encrypted vault)\n- vault (the executable programme)\nNow, these sensitive files are protected and only ever 'exposed' when you actually need them.\nMaybe it's overkill doing this, but if your system is ever compromised, you are protected.\n-> Is it safer than an online password manager?\nThat really depends - online password managers are great and their security is managed by an entire team of developers, but if I was an attacker, would I rather go after a company which manages thousands of people's passwords, or would I rather attack a single person's system to gain access to just theirs?\nOn the other hand, this is limited by the fact that you cannot access the vault everywhere immediately, you'll have to copy the vault.dat file over.\nThis is why I stress Terminally->Locked is not a replacement for traditional password managers, just an extra level of security for your files.\n"},
        { FAQMenuOption::UnlockVaultTime, 
          "Why does unlocking my vault take so long?",
          "This is exactly how the application is designed, so if it takes a few seconds to unlock your vault, then it's working as intended.\nWhy? Because it protects against attackers brute forcing your master password.\nLet's say an attacker gets hold of your data file - if they don't know your password, the best solution is for them to get a dictionary of well-known passwords and write a script which automatically just tries all the passwords one-by-one. If each request only takes 0.001 seconds, then they can try well over 300,000 attempts an hour.\nHowever, because the hashing method of your password is deliberately slow, even with extremely powerful hardware, it may take a couple of seconds to try each password - that means in an hour the attacker may only try around two thousand.\nCan I shorten the time?\nYes - if you are running the programme on an older and less powerful machine, you can speed it up, but the approach is quite technical. I don't recommend doing this, as the extra few seconds wait are worth it for the extra security.\n To do so, you'll need to download the source code, change the SENSITIVE tags in the crypto_pwhash() function in src/crypto/VaultCrypto.cpp to MODERATE.\nThis will make the process quicker, but at the risk of your passwords being less protected. Again, I do not recommend this.\n" },
        { FAQMenuOption::SafePassword,
          "What is a master password?",
          "A master password is the password you use to unlock your vault.\nWhat is a good master password?\nIdeally, a password should be at least eight characters long and should not be something which can easily be guessed - for example:\n - Password1\n - YourName123\n - 1234567890\n These kind of passwords are well known and attackers use dictionaries containing these sorts of examples. An encryption method can be the most complex and powerful in the world, but at the end of the day, the master password must unlock it, so the password is the point of weakness.\nWhat makes a good master password?\nAvoid using anything which is somehow related to you - such as a family member's name followed by their birthday (i.e. 'Jack010190) as, if someone knows enough about you, they may be able to guess. Our whole lives are posted online nowadays, so don't be surprised if people know more about you than you might think.\nA common method for coming up with a strong password is to take three seemingly random words and just put them altogether, such as 'televisioncreamjumping' - you could add uppercase, numbers, and special characters here, but arguably the password wouldn't really be that much more secure in the practical world. Three random words can easily be remembered without being somewhat related to you or guessable (like the name of a family member etc.). The great thing about a password manager is it means that you can just remember one password, and store all the other ones inside.\n" },
        { FAQMenuOption::ForgettingPassword,
          "What if I forget my master password?",
          "Unfortunately, there is no 'forgot password' function for this application. If you forget your password, you lose access to your vault - this is a critical safety feature as explained below.\nYour master password is never stored anywhere in the vault - even encrypting the password and storing it is a massive security risk, as all encryptions can be unencrypted.\nSo how does the programme know the right password?\nWhen you create your vault, your password is hashed and stored in the vault's header file. Hashing is very technical, but the critical difference between hashing and encrypting something is that encryption works both ways - anything which is encrypted can be unencrypted - but hashing only works one way. You cannot 'unhash' something.\nEffectively, when you enter your master password, it hashes it and checks the result against the result stored in the vault. If it is correct, it decrypts the vault. If not, or an error occurs, it doesn't.\nChoose something memorable, not overly complicated, but not easily guessable - see 'What is a master password?' in the FAQs for more information on what makes a good master password.\n" },
    };
    return topics;
}

}
